// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeVw6zoahmR3zHsyg-3LvuhKTuNEdp__o',
    appId: '1:731082490510:web:efa5c325ab35765cf6bfdf',
    messagingSenderId: '731082490510',
    projectId: 'eleguardian-772d5',
    authDomain: 'eleguardian-772d5.firebaseapp.com',
    databaseURL: 'https://eleguardian-772d5-default-rtdb.firebaseio.com',
    storageBucket: 'eleguardian-772d5.firebasestorage.app',
    measurementId: 'G-XJ69LYRPKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkYnYMYAwNCLs3_aBdhPpu4zAYol9fyQ',
    appId: '1:731082490510:android:1bbd507de3da1f37f6bfdf',
    messagingSenderId: '731082490510',
    projectId: 'eleguardian-772d5',
    databaseURL: 'https://eleguardian-772d5-default-rtdb.firebaseio.com',
    storageBucket: 'eleguardian-772d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFDwewrwwQNqz9n-e4raBT51XD6DSrhs',
    appId: '1:731082490510:ios:50a870d92487139ef6bfdf',
    messagingSenderId: '731082490510',
    projectId: 'eleguardian-772d5',
    databaseURL: 'https://eleguardian-772d5-default-rtdb.firebaseio.com',
    storageBucket: 'eleguardian-772d5.firebasestorage.app',
    iosBundleId: 'com.example.capstoneprojectMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFDwewrwwQNqz9n-e4raBT51XD6DSrhs',
    appId: '1:731082490510:ios:50a870d92487139ef6bfdf',
    messagingSenderId: '731082490510',
    projectId: 'eleguardian-772d5',
    databaseURL: 'https://eleguardian-772d5-default-rtdb.firebaseio.com',
    storageBucket: 'eleguardian-772d5.firebasestorage.app',
    iosBundleId: 'com.example.capstoneprojectMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeVw6zoahmR3zHsyg-3LvuhKTuNEdp__o',
    appId: '1:731082490510:web:86a07012c7fcef62f6bfdf',
    messagingSenderId: '731082490510',
    projectId: 'eleguardian-772d5',
    authDomain: 'eleguardian-772d5.firebaseapp.com',
    databaseURL: 'https://eleguardian-772d5-default-rtdb.firebaseio.com',
    storageBucket: 'eleguardian-772d5.firebasestorage.app',
    measurementId: 'G-XP5E38V1KD',
  );
}
