import 'package:provider/provider.dart';
import 'package:health_app/pages/home_page.dart';
// Import our model
import 'pages/user_model.dart';
import 'package:capstoneproject_mobileapp/pages/login_page.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
// Generated by flutterfire configure


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
runApp(
    ChangeNotifierProvider(
      create: (context) => UserProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(

      title: 'EleGaurdian',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: Color(0xFF223A54),
        fontFamily: 'Roboto',
      ),
      home: LoginPage(),
    );
  }
}

